stages:
  - devenv
  - build
  - test
  - lint
  - style
  - coverage
  - release

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

variables:
  GIT_DEPTH: 0

.nix:
  image: registry.gitlab.com/cynerd/gitlab-ci-nix
  tags:
    - docker
  cache:
    key: "nix"
    paths:
      - ".nix-cache"
  before_script:
    - gitlab-ci-nix-cache-before
  after_script:
    - gitlab-ci-nix-cache-after

## Development environment #####################################################
devenv:
  stage: devenv
  extends: .nix
  script:
    - nix develop -c true

## Build stage #################################################################
.build:
  stage: build
  extends: .nix
  needs: ["devenv"]

build:
  extends: .build
  script:
    - nix develop --quiet -c meson setup build -Doptimization=plain $SETUP_ARGS
    - nix develop --quiet -c meson compile -C build
  artifacts:
    when: always
    paths:
    - 'build/'

build-werror:
  extends: build
  needs:
    - job: build
      artifacts: false
  allow_failure: true
  variables:
    SETUP_ARGS: --werror

nix:
  extends: .build
  script:
    - nix build .?submodules=1

nix-appimage:
  extends: .build
  needs: ["nix"]
  script:
    - nix bundle --bundler github:ralismark/nix-appimage/17dd6001ec228ea0b8505d6904fc5796d3de5012 .?submodules=1
  artifacts:
    when: always
    paths:
    - '*.AppImage'

## Test stage ##################################################################
.test:
  stage: test
  extends: .nix
  needs: ["devenv"]

.test-meson:
  extends: .test
  needs:
    - job: build
      artifacts: false
  script:
    - ulimit -n 1024 # workaround for Valgrind
    - nix develop --quiet -c meson setup build -Doptimization=plain $SETUPARG
    - nix develop --quiet -c meson test -C build --print-errorlogs $TESTARG
  artifacts:
    when: always
    paths:
      - 'build/'

tests:
  extends: .test-meson
  variables:
    SETUPARG: -Db_coverage=true # Used in coverage job
  artifacts:
    reports:
      junit: 'build/meson-logs/testlog.junit.xml'

valgrind:memcheck:
  extends: .test-meson
  variables:
    TESTARG: --setup=memcheck

valgrind:helgrind:
  extends: .test-meson
  variables:
    TESTARG: --setup=helgrind

valgrind:drd:
  extends: .test-meson
  variables:
    TESTARG: --setup=drd

nix-check:
  extends: .test
  needs:
    - job: nix
      artifacts: false
  script:
    - nix flake check .?submodules=1

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

## Linters #####################################################################
.linter:
  stage: lint
  extends: .nix
  needs: ["devenv"]
  allow_failure: true

muon-analyze:
  extends: .linter
  script:
    - nix run --quiet .#muon -- analyze

clang-tidy:
  extends: .linter
  needs: ["build"]
  script:
    - nix develop --quiet -c ninja -C build clang-tidy

shellcheck:
  extends: .linter
  script:
    - git ls-files '**.sh' | xargs nix run --quiet .#shellcheck

statix:
  extends: .linter
  script:
    - nix run --quiet .#statix -- check .

## Style stage #################################################################
.style:
  stage: style
  extends: .nix
  needs: ["devenv"]
  allow_failure: true

muon:
  extends: .style
  script:
    - |
      git ls-files '**/meson.build' meson_options.txt |
        xargs nix run --quiet .#muon -- fmt -e -i
    - git diff --exit-code

clang-format:
  extends: .style
  needs: ["build"]
  script:
    - nix develop --quiet -c ninja -C build clang-format
    - git diff --exit-code

shell-format:
  extends: .style
  script:
    - git ls-files '**.sh' '**.bats' | xargs nix run --quiet .#shfmt -- -d

nixfmt:
  extends: .style
  script:
    - nix fmt .
    - git diff --exit-code

deadnix:
  extends: .style
  script:
    - nix run --quiet .#deadnix -- --fail .

editorconfig-checker:
  extends: .style
  script:
    - nix run --quiet .#editorconfig-checker -- -exclude '.nix-cache/.*'

gitlint:
  extends: .style
  script:
    - git fetch
    - nix run --quiet .#gitlint -- --commits origin/master..$CI_COMMIT_SHA

## Code Coverage stage #########################################################
coverage:
  stage: coverage
  extends: .nix
  needs: ["tests"]
  script:
    - nix develop --quiet -c ninja -j1 -C build coverage-html coverage-xml
    - mv build/meson-logs/coveragereport ./
  coverage: '/lines\.\.\.\.\.\.: (\d+.\d+%)/'
  artifacts:
    expire_in: 1 month
    expose_as: 'Code Coverage'
    paths:
    - 'coveragereport/'
    reports:
      coverage_report:
        coverage_format: cobertura
        path: 'build/meson-logs/coverage.xml'

## Release creation ############################################################
release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG'
  image: "registry.gitlab.com/gitlab-org/release-cli:latest"
  needs:
    - job: tests
      artifacts: false
    - job: nix-appimage
      artifacts: true
  before_script:
    - apk update
    - apk add bash curl yq
  script:
    - ./release.sh
